export const cities = [
  "Trincomalee",
  "Mutur Bus stand",
  "kadiravely stand",
  "Vakarei police station",
  "Ottamavadi",
  "Batticolo Busstand",
  "Kaththankudy",
  "Kalmunei",
  "Ampara",
  "Akkareipattu",
  "3 mile post",
  "6th mile post",
  "Irrakkandy",
  "Kuchchaweli",
  "Pudaweikattu",
  "T junction",
  "Thiriyaya",
  "Pulmudei",
  "Anuradhapura",
  "Kurunegala",

];
